<a href="https://colab.research.google.com/github/Anisha-singh2207/Algorush/blob/main/Ridge%20and%20Lasso%20Regularisation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('/content/load_boston_final_lyst1729240745225.csv')

In [3]:
df

Unnamed: 0     CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  \
0             0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0   
1             1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0   
2             2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0   
3             3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0   
4             4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0   
..          ...      ...   ...    ...   ...    ...    ...   ...     ...  ...   
501         501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0   
502         502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0   
503         503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0   
504         504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0   
505         505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0   

       TAX  PTRATIO       B  LSTAT  target_col  
0    296.0     15.3  396.90   4.98        24.0  
1    242.0     17.8  396.90   9.14        21.6  
2    242.0     17.8  392.83   4.03        34.7  
3    222.0     18.7  394.63   2.94        33.4  
4    222.0     18.7  396.90   5.33        36.2  
..     ...      ...     ...    ...         ...  
501  273.0     21.0  391.99   9.67        22.4  
502  273.0     21.0  396.90   9.08        20.6  
503  273.0     21.0  396.90   5.64        23.9  
504  273.0     21.0  393.45   6.48        22.0  
505  273.0     21.0  396.90   7.88        11.9  

[506 rows x 15 columns]

In [4]:
x=df.iloc[:,1:14]
y=df.iloc[:,-1]

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=1)

In [6]:
# sacling so that the different scales of the dataset entries become available
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [7]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [20]:
from sklearn.model_selection import cross_val_score

c_v = cross_val_score(lr, x_train, y_train, scoring='neg_mean_squared_error', cv=10)
c_v_1=cross_val_score(lr,x_train,y_train,scoring='neg_mean_absolute_error',cv=10)

In [21]:
y_pred=lr.predict(x_test)

In [22]:
y_pred

array([32.65503184, 28.0934953 , 18.02901829, 21.47671576, 18.8254387 ,
       19.87997758, 32.42014863, 18.06597765, 24.42277848, 27.00977832,
       27.04081017, 28.75196794, 21.15677699, 26.85200196, 23.38835945,
       20.66241266, 17.33082198, 38.24813601, 30.50550873,  8.74436733,
       20.80203902, 16.26328126, 25.21805656, 24.85175752, 31.384365  ,
       10.71311063, 13.80434635, 16.65930389, 36.52625779, 14.66750528,
       21.12114902, 13.95558618, 43.16210242, 17.97539649, 21.80116017,
       20.58294808, 17.59938821, 27.2212319 ,  9.46139365, 19.82963781,
       24.30751863, 21.18528812, 29.57235682, 16.3431752 , 19.31483171,
       14.56343172, 39.20885479, 18.10887551, 25.91223267, 20.33018802,
       25.16282007, 24.42921237, 25.07123258, 26.6603279 ,  4.56151258,
       24.0818735 , 10.88682673, 26.88926656, 16.85598381, 35.88704363,
       19.55733853, 27.51928921, 16.58436103, 18.77551029, 11.13872875,
       32.36392607, 36.72833773, 21.95924582, 24.57949647, 25.14

In [23]:
lr.score(x_train,y_train)

0.7293585058196337

In [24]:
from sklearn.metrics import mean_squared_error,mean_absolute_error
print(mean_absolute_error(y_test,y_pred))
print(mean_squared_error(y_test,y_pred))

3.7507121808389154
23.38083648027022


In [25]:
c_v

array([-11.43704327, -24.95657283, -38.11072307, -16.74662905,
       -19.60396439, -15.46374474, -34.34894056, -34.26909616,
       -32.38669098, -14.73132457])

In [26]:
c_v.mean()

np.float64(-24.205472962155845)

In [27]:
c_v_1

array([-2.50318625, -3.4160736 , -3.53392037, -3.2583849 , -3.43542598,
       -2.94822843, -3.87598824, -3.98839231, -3.5832304 , -2.89364249])

In [28]:
c_v_1.mean()

np.float64(-3.3436472994299997)

Ridge regularisation

In [30]:
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV

In [34]:
ridge_1=Ridge()

In [35]:
parameters={"alpha":[1,2,3,4,5,6,7,10,30,40,50,70,45]}
ridge_cv=GridSearchCV(ridge_1,parameters,scoring="neg_mean_squared_error",cv=10)
ridge_cv.fit(x_train,y_train)

GridSearchCV(cv=10, estimator=Ridge(),
             param_grid={'alpha': [1, 2, 3, 4, 5, 6, 7, 10, 30, 40, 50, 70,
                                   45]},
             scoring='neg_mean_squared_error')

In [36]:
ridge_cv.best_params_

{'alpha': 4}

In [37]:
ridge_pred=ridge_cv.predict(x_test)

In [40]:
from sklearn.metrics import r2_score
r2_score(ridge_pred,y_test,)

0.5834589404958654

In [41]:
r2_score(y_test,y_pred)

0.7634174432138472

Lasso Regression model:


In [42]:
from sklearn.linear_model import Lasso


In [46]:
lasso_l=Lasso()

In [48]:
parameters={"alpha":[1,2,3,4,5,6,7,10,30,40,50,70,45]}
lasso_cv = GridSearchCV(lasso_l, parameters, scoring="neg_mean_squared_error", cv=5)
lasso_cv.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=Lasso(),
             param_grid={'alpha': [1, 2, 3, 4, 5, 6, 7, 10, 30, 40, 50, 70,
                                   45]},
             scoring='neg_mean_squared_error')

In [50]:
lasso_pred=lasso_cv.predict(x_test)

In [51]:
r2_score(y_test,lasso_pred)

0.6546512972478653